# Classification
- Trying to prepict a category


## MINST (handwitten digits)
- Classic machine learning benchmark
- Given: input image -> Predict: what digit


## 2 common types of data
- Images (ex. MINST) -- computer vision
- Text (ex. emails) -- natural language processing (NLP)
- The entire internet is (mostly) made up of these 2 things

## Text Eample: Spam Detection
- Input: email
- Preedict: Spam or not spam

## Business Example: Online Ads
- Improve the service and make more money
- Input:
  - Age
  - Gender
  - Location
  - You searched "best sunglasses for running"
- Predicts:
  - Will you click on the ad? Yes/No
- Binary classification

## Common Theme
- Input: handwritten digit, email, online ads
- Machin Learning classifier (Just a black box for now)
- Output predictions:
  - Click/No click
  - But/No Buy
  - Spam/Not spam

## Learning
- How does machine learning make correct predictions?
- We're given a dataset on which to train
- It consistes of **input data** and **tagets(aka labels)**
- Learning: given many examples, figure out the pattern

Input data -> Targets

- I am a Nigerian prince...  -> Spam
- Your latest commit just took down the production server! -> Not Spam
- Make money online NOW! -> Spam

## But... what is the algorithm that allows us to learn?
- This is what machine learning is about
- What are these algorithms? How do they work?
- 20 or more courses

## Useful abstraction
- 2 useful thing the black box can do
  1. Learn
    - Figure out the pattern between input (X) and target (Y)
  2. Predict
    - Label new things it has never seen before (e.g. tomorrow's emails)
  


## How about the code?
- Let's tart with data
- Given:
  - X(a 2-D array of shap N x D) (*important*: The array cotains NUMBER ONLY)
    * N = number of training examples (samples)
    * D = number of features
  - Y(a 1-D array of length N) containing the corresponding targets. e.g. Y[n] is the target of X[n]

-------------------------------------------------------

  
  |          | nigerian_prince | insurance | loan | ... | |Tagets|
  -----------|-----------------|-----------|------|-----|--|-|
  |Email #1 |1|0|0|| =>|1                                      
  |Email #2 |0|1|1|| =>|1
  |Email #3 |0|0|0|| =>|0



## The Code
- Remember, we have to do two things, learn and make the new predictions

```
# import RandomForestClassifierfrom sklearn from somewhere above

model = RandomForestClassifer()
model.fit(X, Y) # leaning
predicitions = model.predict(X) # make prediction
```


## Evaluation
- How do we know the model learn something useful?
- Measure its accuracy(aka Classification rate)

- Accuracy = # correct / # total
- In code ( can dot it manually)
  - model.score(X,Y)


# Classification In Code

In [ ]:
import numpy as np

# import the function that will get the data
# yes, sklearn come with built-in datasets
from sklearn.datasets import load_breast_cancer

In [ ]:
# load the data
data = load_breast_cancer()

In [ ]:
# check the type 'data'
type(data)

sklearn.utils._bunch.Bunch

In [ ]:
# note: it is a Bunch object
# this basically acts like a dictionary where you can trat keys like attributes
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
data.data.shape

(569, 30)

In [ ]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
data.target.shape

(569,)

In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# split the dtata into train and test sets
# this lets us simulate how our model fits
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.33) # 67% train data, 33% test data

In [ ]:
# instantiate a classifer an train it
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier()


In [ ]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
# evalute the mode's performance
model.score(X_train, y_train)

1.0

In [ ]:
model.score(X_test, y_test)

0.9627659574468085

In [ ]:
# How do you make prediction
predictions = model.predict(X_test)

In [ ]:
# What did you get?
predictions

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1])

In [ ]:
N = len(y_test)
N

188

In [ ]:
np.sum(predictions == y_test) / N

0.9627659574468085

In [ ]:
# We can even use deep learning to solve the same problem!
from sklearn.neural_network import MLPClassifier

In [ ]:
# You'll learn why scaling is needed in a later course
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train2 = scaler.fit_transform(X_train)

In [ ]:
X_test2 = scaler.transform(X_test)

In [ ]:
model = MLPClassifier(max_iter = 1000)

In [ ]:
model.fit(X_train2, y_train)

MLPClassifier(max_iter=1000)

In [ ]:
# evalute tje model's performance
model.score(X_train2, y_train)

0.9973753280839895

In [ ]:
model.score(X_test2, y_test)

0.9840425531914894

- If we run this in command Python shell, we get warning that the training hadn't converged. So make it train longer.
- Lesson to remember: deep learning is not a "plug and ply" type og algorithm.
- Add max_iter = 500 to MLPClassifier()
- Add mac_iter = 1000

# What is regression?

## Regression
- We just covered classification, which seems to be very intuitive.
  - "What is t it?" (digit, written characters)
  - "Yest or no?" (Spam vs not spam, click vd no click)
- Regression is also very intuitive in a very visual way.


## Regression vs Classification
- Classification: pritict a category
- Regression: predict a number on the real line (e.g. 1, -2, 3.13)
- You may object!
  - In code, spam =1 not spam = 1 - aren't they number?
  - These numbers are just symbols to represent the category
  - We can switch them with no effect
- In regression, the numbers do have meanings (we see this via examples)



## Ex: Height vs Weight
-- Given a person's height, we want to predict weight
-- Scatterplot of height vs weight

## Ex: Predict house price
- Real Estate application
- Can have > 1 input
  - Average family income
  - Crime rate
  - Size
  - Number of bedrooms
  - When last renovated

## Many-dimentional input
- With so many input, you can not visualize it
- 1 input -> line
- 2 inputs -> plane
- \> 2 inputs -> hyper plane, not visulizable

## Obligatory Business Example
- The stock market
- Rule: Buy low, sell high
- Normally, people violate this rule because of emotions such as fear
- From an ML(regression) perspective, what do we want to do?
  - input:
    * Price for the last 10 days
    * Was it mentioned in the news yesterday?
    * Was it postive or negative?
  - Predict:
    * Tomorrow's stock price


## What will the code look like?
- Again. let's start with data
  - X (2-D array of shape N x D)
    * N = number of samples
    * D = number of features
  - Y (1-D array of length N)



---------------------------------------


  |          | # hours studied| # hours playing games | # classes missed|  |Grade|
  -----------|-----------------|-----------|------|-----|-|
  |Student #1 |10|3|0|=>|87                                     
  |Student #2 |8|20|2|=>|75
  |Student #3 |5|1|5|=>|63


## The code
- Exactly the same as before! (For the classification example)
  - Except now we use a regression model, not a classifier

```
model = LinearRegression()
model.fit(X, Y) # learning
predictions = model.predict(X) # make predictions
score = model.score(X, Y) # evalute

```

## What is the score?
- Accuracy no longer make sense (# correct / # total)
- Doen't make sense for regression
  - If true house price is 1 million dollars, and we predict 1 miliion and 1 dollar. - are we wrong?
  - Intuitively we know it's pretty good.
  - If we predict 2 million then it's bad
- Regression uses MSE(Mean Squared Error). But it's not returned by score()
  - Y with the "hat" on top is the prediction

$$
MSE = 1/N \sum_{i=1}^{N}(\hat{Y_i} - Y_i)^2
$$

### Why not MSE?
- The house prices will range hundred of thousands to millions
- The grades will range between 0..100
- An error of $100^2$ is not bad for house prices, but very bad for grades
- The relative scale matters

### The $\ $ $R^2$
- Is literally corelation coefficent
- SSE: Sum of squared errors
  - For each predition, we take the difference between it and the corresponding target, square difference and add all squared differnces together
- SST: Sum of the squared total
  - The sum of squared differences between each target and the sample mean of the targets
  - It's proportional to the variance of the targets
  - If we divide SST by N, it's $1 - \frac{MSE}{variance}$

- Perfect model: $\ SSE = 0, \ R^2 = 1 $
- Dumbest model: Predict average every time, $\ SSE= SST, \ R^2 = 0$
- $\ R^2 < 0$, if predictions are so widely incorrect, $\ SSE> SST $, it's even worse then dumbest model

$$
$$

$$
R^2 = 1\  - \ \frac{SSE}{SST}
$$
$$
SSE = \frac{1}{N} \sum_{i=1}^{N}(y_i - \hat{y_i} )^2
$$
$$
SST = \sum_{i=1}^{N}(y_i - \bar{y} )^2, \bar{y}\ means\ mean\ of\ all\ y^{'}
$$

# Regression In Code

In [36]:
# Get data from:
# https://archive.ics.uci.edu/dataset/291/airfoil+self+noise
# Download the data file and unzip in Downloads directory
# upload data file to google drive in "My Drive/Colab Notebooks"

from google.colab import drive
drive.mount("/content/drive#")

Mounted at /content/drive


In [40]:
from google.colab import files
uploaded = files.upload()

In [41]:
!ls


airfoil_self_noise.dat	content  drive	sample_data


In [37]:
!pwd

/content


In [24]:
import numpy as np
import pandas as pd

In [39]:
df = pd.read_csv("airfoil_self_noise.dat", sep='\t', header=None)

In [27]:
df.head()

0    1       2     3         4        5
0   800  0.0  0.3048  71.3  0.002663  126.201
1  1000  0.0  0.3048  71.3  0.002663  125.201
2  1250  0.0  0.3048  71.3  0.002663  125.951
3  1600  0.0  0.3048  71.3  0.002663  127.591
4  2000  0.0  0.3048  71.3  0.002663  127.461

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       1503 non-null   int64  
 1   1       1503 non-null   float64
 2   2       1503 non-null   float64
 3   3       1503 non-null   float64
 4   4       1503 non-null   float64
 5   5       1503 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 70.6 KB
