# Introdcution

## Type of fuctions

- Dot Product
- Multiplication
- Element-Wise Product
- Linear System: Ax = b
- Inverse: $\ A^{-1} $
- Determinant: |A|
- Choosing Random Numbers (e.g. Uniform, Gaussian)

## Applicarions

1. Linear Regression
2. Logistic Regression
3. Deep Neural Networks
4. K-Means Clustering
5. Density Estimation
6. Principal Components Analysis
7. Matrix Factorizaation (Recommander Systesm)
8. Control Systems
9. Markov Models. HMN
10. Control Sytems (Not ML)
11. Game Theory (Not ML)
12. Opearations Research (Share many things with ML)
13. Portfoli Optimization





# Array vs Lists

In [ ]:
import numpy as np

In [ ]:
L = [1, 2, 3]

In [ ]:
A = np.array(L)

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)


In [ ]:
L

[1, 2, 3, 4]

In [ ]:
# A.append(4)

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4]) # Broadcasting

array([5, 6, 7])

In [ ]:
A + np.array([4, 5, 6])

array([5, 7, 9])

In [ ]:
# A + np.array([4, 5])

In [ ]:
2 * A

array([2, 4, 6])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for e in L:
  L2.append(e + 3)

L2

[4, 5, 6, 7]

In [ ]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [ ]:
# L**2

In [ ]:
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

In [ ]:
A ** 2

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# Dot Product

$$
a ̇b = a^{T}b = \sum_{d=1}^{D}a_{d}b_{d}
$$

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

In [ ]:
dot = 0
for e, f in zip(a,b):
    dot += e * f

dot

11

In [ ]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a*b)

11

In [ ]:
(a * b).sum()

11

In [ ]:
np.dot(a, b)

11

In [ ]:
a.dot(b)

11

In [ ]:
a @ b

11

$$
a^{T}b = \lVert a\rVert \ \lVert b\rVert \cosθ_{ab}
$$
$$
\cosθ_{ab} = \frac{a^{T}b}{\lVert a\rVert \ \lVert b\rVert}
$$
$$
$$
$$
\lVert a\rVert = \sqrt{\sum_{d=1}^{D} a_{d}^2}
$$

In [ ]:
amng = np.sqrt((a * a).sum())
amng

2.23606797749979

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
cosangle = a.dot(b) / (np.linalg.norm(a) * (np.linalg.norm(b)))
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)
angle # radiant

0.17985349979247847

# Speed Test

In [ ]:
## speed comparison
from datetime import datetime

# note: you can use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_production(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_production(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / d2: ", dt1.total_seconds() / dt2.total_seconds())


dt1 / d2:  19.674700763568822


# Matrics

- Using numpy.matrix is not recommanded
- Convert matrics to numpy array

In [ ]:
L = [[1, 2], [3, 4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array(L)
A # the output is presented as a 2-D array

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0, 1]

2

In [ ]:
# select column 0 in the matrix
A[:, 0]

array([1, 3])

In [ ]:
# Transpose
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1, 2, 3], [4, 5, 6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# A * B is element-wisr multiplication. It's dieffrent from matrix multiplication.
# matrix multiplication is a generalization of the dot product.
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
# In matrix multiplication, the inner dimensions must match
# A.dot(B.T)

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-92-917a5a1c1791> in <cell line: 2>()
      1 # In matrix multiplication, the inner dimensions must match
----> 2 A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)
```

In [ ]:
# determinant for square matrix
np.linalg.det(A)

-2.0000000000000004

In [ ]:
# inverse
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
# identity matrix
np.linalg.inv(A).dot(A)
# [ 1 , 0]
# [ 0,  1]
# inverse operation is not accurate

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
# trace for square matrix
np.trace(A)

5

In [ ]:
# matrix diagnal
np.diag(A)

array([1, 4])

In [ ]:
# diag is overloaded. input: matrix -> output: vector, input: vector -> output:matrix
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

### [Why & When to use Eigenvalues and Eigenvectors](https://vitalflux.com/why-when-use-eigenvalue-eigenvector/#:~:text=Eigenvalues%20represent%20the%20scaling%20factor,in%20which%20the%20transformation%20occurs.)

In [ ]:
# eigenvalues and eigenvectors of a.
# the first return value is an array containing all the eigenvalues, and the second return
# value is an array containing all the eigenvectors organized into a matrix

np.linalg.eig(A)


(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
Lam, V = np.linalg.eig(A)

In [ ]:
# precision decrepency to create [Trus, False] when it should be [True, True]
V[:,0] * Lam[0] == A @ V[:, 0]

array([ True, False])

In [ ]:
# These two are actually the same
V[:,0] * Lam[0], A @ V[:, 0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
np.allclose(V[:,0] * Lam[0], A @ V[:, 0])

True

In [ ]:
np.allclose(V @ np.diag(Lam), A @ V)

True



### [numpy.linalg.eig API](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)

```
As a final side note for this lecture, if you know that your matrix is symmetric, then you can use

the function np dot io.h which is better for that scenario.

The H here stands for Hermitian, which is the complex analog of the matrix transpose.

It does both a transpose and takes the complex conjugate of the elements.

So just so you're aware, numpy does handle complex numbers if you're doing signal processing or quantum mechanics or something like that.

In practice, usually you'll use eigen decomposition on a symmetric matrix like the covariance.

So when that's the case, you should use H instead, which has the same API.
```


# Solving Linear System

$$
x_{1} + x_{2} = 2200
$$
$$
1.5x_{1} + 4x_{2} = 5050
$$
$$
$$
$$
x = \begin{pmatrix} x1 \\ x2\end{pmatrix}, \
A = \begin{pmatrix} 1 & 1\\ 1.5 & 4 \end{pmatrix}, \
b = \begin{pmatrix} 2200 \\ 5050 \end{pmatrix}
$$
$$
$$
$$
Ax = b <=> x = A^{-1}b
$$

## Don't do this
- ### The "inverse" is slower
- ### There are better algorithms to **solve** linear system
- ### x = np.linalg.solve(A, b) # yes
- ### x = np.linalg.inv(A).dot(b) # no


In [ ]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])
np.linalg.solve(A, b)

array([1500.,  700.])

In [ ]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

# Generating Data

-  A neural network is made up of many large matrices, which you will randomly initialize and then train using an algorithm called Backpropagation.

- Another common reason to create your own arrays is to generate synthetic data to test your algorithm on.

- Often using synthetic data is extremely useful because it allows us to test the efficacy of our models.

- Since you generated the data yourself, you know the true answer and you can see how close your model gets to that true answer.

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.928682173792794

In [ ]:
np.random.random((2, 3))

array([[0.80041537, 0.76744306, 0.95732615],
       [0.05352403, 0.26156964, 0.05161498]])

In [ ]:
np.random.randn(2, 3)

array([[-0.03549968,  1.50837715,  0.23098457],
       [ 1.96759182, -0.03657968, -0.47741078]])

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

0.013852030895721512

In [ ]:
np.mean(R)

0.013852030895721512

In [ ]:
R.var()

1.0172118098913703

In [ ]:
R.std()

1.00856918944184

In [ ]:
R = np.random.randn(10000, 3)

In [ ]:
R.mean(axis=0) # mean of each of 3 columns

array([ 0.0130682 , -0.00619874, -0.01168546])

In [ ]:
R.mean(axis=1) # mean of each of 10000 rows

array([ 0.1784497 ,  0.51514813,  0.25486648, ..., -0.66831239,
        0.93966994,  0.02064877])

In [ ]:
R.mean(axis=1).shape

(10000,)

|         | Openness | Conscientiousness | Extroversion | Agreeableness | Neuroctism|
|---------|-------- |-------------------|--------------|---------------|---------|
| Alice   |8| 5 |7 | 7| 7|
| Bob | 3|4|2|2|2|
| Carol |4|2|7|5|2|


In [ ]:
np.cov(R)

array([[ 0.23226943,  0.34545519, -0.04117939, ..., -0.13404108,
         0.46124059, -0.05879185],
       [ 0.34545519,  1.39976473, -0.57952842, ..., -0.21237102,
         1.58456031, -1.05244674],
       [-0.04117939, -0.57952842,  0.31049051, ...,  0.03137577,
        -0.60741976,  0.57494155],
       ...,
       [-0.13404108, -0.21237102,  0.03137577, ...,  0.07754526,
        -0.27937483,  0.04810033],
       [ 0.46124059,  1.58456031, -0.60741976, ..., -0.27937483,
         1.82725329, -1.0954647 ],
       [-0.05879185, -1.05244674,  0.57494155, ...,  0.04810033,
        -1.0954647 ,  1.06597513]])

In [ ]:
np.cov(R).shape

(10000, 10000)

In [ ]:
np.cov(R.T)

array([[ 1.01174683, -0.00837571,  0.02166137],
       [-0.00837571,  1.0042453 , -0.01561882],
       [ 0.02166137, -0.01561882,  0.99914719]])

In [ ]:
np.cov(R, rowvar=False)

array([[ 1.01174683, -0.00837571,  0.02166137],
       [-0.00837571,  1.0042453 , -0.01561882],
       [ 0.02166137, -0.01561882,  0.99914719]])

In [ ]:
np.random.randint(0, 10, (3, 3))

array([[8, 8, 3],
       [7, 3, 8],
       [8, 2, 7]])

In [ ]:
np.random.choice(10, (3, 3))

array([[3, 8, 8],
       [8, 6, 9],
       [1, 0, 5]])